[env:mono-note-mini]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
monitor_speed = 115200
build_flags =
    -DBOARD_HAS_PSRAM
lib_deps =
    bblanchon/ArduinoJson@^7.2.0

